

// function getInputNumber(id) {
//     var amount = id;
//     //var amountNumber = parseFloat(amount);
//     if (amount == NaN) {
//         amount = 0;
//     } else {
//         amountNumber = parseFloat(amount);
//     }
//     return amount;
// }

// const withdrawNumber = getInputNumber(NaN);

// console.log(withdrawNumber);

var name = NaN;

if(isNaN(name) == true) {
    console.log("NaN works")
} else {
    console.log("nope :/")
}